export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/checkbox/index',
    'pages/radio/index',
    'pages/dot-loading/index',
    'pages/button/index',
    'pages/list/index',
    'pages/mask/index',
    'pages/popup/index',
    'pages/space/index',
    'pages/divider/index',
    'pages/auto-center/index',
    'pages/grid/index',
    'pages/safe-area/index',
    'pages/capsule-tabs/index',
    'pages/jumbo-tabs/index',
    'pages/tabs/index',
    'pages/badge/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
  },
});
